services:
  frontend:
    build:
      context: ./frontend
      target: runner
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  backend:
    build:
      context: ./backend
      target: runner
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
