"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { useRouter, usePathname } from "next/navigation";
import { 
  Search, 
  Sun, 
  Moon, 
  Bell, 
  User, 
  ShieldCheck, 
  LogOut,
  ChevronRight,
  TrendingUp,
  Bookmark,
  AlertCircle
} from "lucide-react";
import { useDashboardStore } from "@/store/useDashboardStore";
import { useAuthStore } from "@/store/useAuthStore";
import { createClient } from "@/utils/supabase/client";

export function TopNav() {
  const router = useRouter();
  const pathname = usePathname();
  const { isDarkMode, setDarkMode, searchQuery, setSearchQuery, favorites, toggleFavorite } = useDashboardStore();
  const { user, setUser } = useAuthStore();
  
  const [showAlertDropdown, setShowAlertDropdown] = useState(false);
  const [showProfileDropdown, setShowProfileDropdown] = useState(false);
  
  // Mock alerts
  const [alerts, setAlerts] = useState([
    { id: "1", text: "Security alert: API Key generated by Sanjay Patel", time: "10m ago", read: false, type: "security" },
    { id: "2", text: "n8n automation pipeline returned a 404 connection timeout", time: "1h ago", read: false, type: "error" },
    { id: "3", text: "ARR Forecast Model training runs successfully finished", time: "3h ago", read: true, type: "success" }
  ]);

  const handleSignOut = async () => {
    try {
      if (process.env.NODE_ENV !== 'production') {
        await fetch('/api/mock-auth', { method: 'DELETE' });
      }
      const supabase = createClient();
      await supabase.auth.signOut();
      setUser(null);
      router.push('/login');
      router.refresh();
    } catch (error) {
      console.error("Error signing out:", error);
    }
  };

  const getBreadcrumbName = () => {
    const path = pathname.split('/').pop() || 'dashboard';
    return path.replace('-', ' ');
  };

  const activeTabId = pathname.split('/').pop() || 'dashboard';

  return (
    <header className={`sticky top-0 z-40 border-b backdrop-blur-md transition-all ${
      isDarkMode ? "border-zinc-800/40 bg-[#05070f]/85" : "border-slate-200/80 bg-white/85"
    }`}>
      <div className="px-6 h-16 flex items-center justify-between gap-4">
        
        {/* Dynamic Breadcrumbs & Favorites Pin */}
        <div className="flex items-center gap-3">
          <Link href="/" className="md:hidden flex h-8 w-8 items-center justify-center rounded-lg bg-cyan-500/10 text-cyan-500">
            <TrendingUp className="h-4.5 w-4.5" />
          </Link>
          <div className="flex items-center gap-1.5 text-xs font-semibold">
            <span className="text-zinc-500 font-mono">WORKSPACE</span>
            <ChevronRight className="h-3 w-3 text-zinc-600" />
            <span className="text-zinc-500 font-mono uppercase">CONSOLE</span>
            <ChevronRight className="h-3 w-3 text-zinc-600" />
            <span className="text-cyan-500 uppercase font-mono">{getBreadcrumbName()}</span>
          </div>
          <button 
            onClick={() => toggleFavorite(activeTabId)}
            className={`p-1.5 rounded hover:bg-zinc-800/40 transition-colors ${
              favorites.includes(activeTabId) ? "text-cyan-500" : "text-zinc-500"
            }`}
            title="Bookmark / Favorite active view"
          >
            <Bookmark className={`h-4 w-4 ${favorites.includes(activeTabId) ? "fill-cyan-500" : ""}`} />
          </button>
        </div>

        {/* Global Search & Action Triggers */}
        <div className="flex items-center gap-4">
          
          <div className="relative hidden sm:block w-48 md:w-60">
            <Search className="absolute inset-y-0 left-3 my-auto h-3.5 w-3.5 text-zinc-500" />
            <input 
              type="text"
              placeholder="Global search logs & jobs..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className={`w-full pl-9 pr-3 py-1.5 text-xs rounded-lg border focus:outline-none transition-all ${
                isDarkMode 
                  ? "bg-zinc-900/60 border-zinc-800 text-white focus:border-cyan-500" 
                  : "bg-white border-slate-200 text-slate-800 focus:border-indigo-500"
              }`}
            />
          </div>

          <button 
            onClick={() => setDarkMode(!isDarkMode)}
            className={`p-2 rounded-lg border transition-all ${
              isDarkMode ? "border-zinc-800 bg-zinc-900/60 text-yellow-400" : "border-slate-200 bg-white text-slate-700 shadow-sm"
            }`}
          >
            {isDarkMode ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
          </button>

          {/* Notification Center */}
          <div className="relative">
            <button 
              onClick={() => { setShowAlertDropdown(!showAlertDropdown); setShowProfileDropdown(false); }}
              className={`p-2 rounded-lg border relative transition-all ${
                isDarkMode ? "border-zinc-800 bg-zinc-900/60 text-zinc-400" : "border-slate-200 bg-white text-slate-755 shadow-sm"
              }`}
            >
              <Bell className="h-4 w-4" />
              {alerts.some(a => !a.read) && (
                <span className="absolute top-1.5 right-1.5 h-2 w-2 bg-rose-500 rounded-full animate-ping" />
              )}
            </button>

            {showAlertDropdown && (
              <div className={`absolute right-0 mt-2 w-80 rounded-2xl border shadow-2xl p-4 z-50 ${
                isDarkMode ? "bg-zinc-950 border-zinc-800" : "bg-white border-slate-200"
              }`}>
                <div className="flex justify-between items-center border-b border-zinc-850 pb-2 mb-3">
                  <span className="text-xs font-bold text-white flex items-center gap-1"><AlertCircle className="h-3.5 w-3.5 text-cyan-400" /> Notifications Feed</span>
                  <button 
                    onClick={() => { setAlerts(alerts.map(a => ({ ...a, read: true }))); }}
                    className="text-[9px] text-cyan-500 hover:underline"
                  >
                    Mark all read
                  </button>
                </div>
                <div className="space-y-3 max-h-[220px] overflow-y-auto">
                  {alerts.map(a => (
                    <div key={a.id} className={`p-2.5 rounded-lg border text-[11px] leading-relaxed ${
                      a.read ? "bg-transparent border-zinc-900 text-zinc-500" : "bg-cyan-500/5 border-cyan-500/10 text-zinc-300"
                    }`}>
                      <div className="flex justify-between font-bold mb-0.5">
                        <span className="capitalize text-cyan-400 font-mono text-[9px]">{a.type}</span>
                        <span className="text-zinc-600 font-mono text-[9px]">{a.time}</span>
                      </div>
                      <p>{a.text}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* User Profile */}
          <div className="relative">
            <button 
              onClick={() => { setShowProfileDropdown(!showProfileDropdown); setShowAlertDropdown(false); }}
              className="flex items-center gap-2 p-1.5 rounded-lg border border-zinc-850 bg-zinc-900/60 hover:bg-zinc-900/80 transition-colors"
            >
              <div className="h-6 w-6 rounded-full bg-cyan-500/15 border border-cyan-500/25 flex items-center justify-center font-bold text-xs text-cyan-500">
                {user?.name ? user.name.split(' ').map(n => n[0]).join('') : "U"}
              </div>
              <span className="text-[10px] text-zinc-400 font-bold hidden sm:inline">{user?.name || "User"}</span>
            </button>

            {showProfileDropdown && (
              <div className={`absolute right-0 mt-2 w-48 rounded-xl border shadow-2xl p-2 z-50 ${
                isDarkMode ? "bg-zinc-950 border-zinc-800" : "bg-white border-slate-200"
              }`}>
                <Link 
                  href="/settings"
                  onClick={() => setShowProfileDropdown(false)}
                  className="w-full text-left px-3 py-2 text-xs rounded hover:bg-zinc-900 text-zinc-400 hover:text-white flex items-center gap-1.5"
                >
                  <User className="h-3.5 w-3.5" /> Profile Center
                </Link>
                <div className="border-t border-zinc-850 my-1.5" />
                <button 
                  onClick={handleSignOut}
                  className="w-full text-left px-3 py-2 text-xs rounded hover:bg-zinc-900 text-rose-400 flex items-center gap-1.5"
                >
                  <LogOut className="h-3.5 w-3.5" /> Sign-out Workspace
                </button>
              </div>
            )}
          </div>

        </div>
      </div>
    </header>
  );
}
